[package]
name = "exgpgme"
version = "0.1.0"
authors = []

[lib]
name = "exgpgme"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.15.1"
rustler_codegen = "0.15.1"
lazy_static = "0.2"
gpgme = { git = "https://github.com/johnschug/rust-gpgme.git" }
